### ISSUE TITLE
User Auth MVP Review

### ISSUE THREAD

**Issue by Brent1LT** [Brent1LT/Turo-Clone#2]
I finished user auth and pushed it to Heroku.

here is the link: https://turo-clone.herokuapp.com/#/

**Comment by evhumphrey** [comment]
Nice! Good job!

Some feedback: 

### Modals
- [x] Your `x` should be a `sans-serif` font, and a little bit more from the right
- [x] Make sure the buttons have `cursor: pointer` 
- [x] Give your inputs a `placeholder` 
- [x] Remove the border from your green buttons
- [x] Add left/right padding on your inputs (so the text isn't smushed against the sides of the input)

### Logout
- [x] The text isn't vertically centered for each option in the dropdown


How the modal should look (though I'd probably use a wider font for the x)
![screen shot 2019-03-01 at 11 56 12 am](https://user-images.githubusercontent.com/6361824/53662976-3dc9e000-3c19-11e9-913e-9e4fb7780047.png)

**Comment by Brent1LT** [comment]
Got it!
